name: jacobvoller.com/doge

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Pull git repository
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          export TERM=xterm
          sudo chmod +x ./doge.sh
          ./doge.sh

      - name: Deploy Web
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "Automated update to /docs/"
          git push

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "ServerArtifacts/*"
          target: "~/myapp"

      - name: Restart app on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            pkill dotnet || true
            nohup dotnet ~/myapp/YourApp.dll > ~/myapp/log.txt 2>&1 &

      # - name: Purge CloudFlare cache
      #   uses: jakejarvis/cloudflare-purge-action@master
      #   env:
      #     CLOUDFLARE_ZONE: f4d879a855eb66074e10f649c03cdd6a
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}